version: "3.9"

services:
  api:
    build: .
    container_name: starx_api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      SERVER_URL: http://api:3000
    command: ["npm", "run", "start:api"]

  worker:
    build: .
    container_name: starx_worker
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      SERVER_URL: http://api:3000
    command: ["npm", "run", "start:worker"]

  db:
    image: postgres:16
    container_name: starx_db
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    container_name: starx_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
